apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc1
spec:
  replicas: 5
  selector: 
    team: prod
  template:
    metadata:
      name: mypod2
      labels:
        app: web
        region: US
        team: prod
    spec:
      containers:
        - name: "c2"
          image: "vimal13/apache-webserver-php"
